### PR TITLE
don't setup click handler when running FastBoot

### PR DESCRIPTION
**Pull request by rlivsey**
`document` isn't available under FastBoot so it kills the app.

There may be nicer ways of doing this?

### CODE REVIEW

**Comment by jasonmit** [comment]
Moving the initializer to `app/instance-initializers/browser/ember-href-to.js` should also work.  At least based on the source code I've read in the past.  Haven't actually used it myself.

https://github.com/ember-fastboot/ember-cli-fastboot/blob/master/index.js#L67-L73

**Comment by GavinJoyce** [comment]
Thanks for this. Perhaps you could verify @jasonmit's suggestion to move the initializer? It looks like it's the official way of doing this.

**Comment by rlivsey** [comment]
I'm assuming this works in all versions of Ember without having the fastboot addon installed?

I'll have a play tomorrow.

**Comment by jasonmit** [comment]
I believe so since its a funnel without a destDir.  But needs to be verified.

**Comment by rlivsey** [comment]
That appears to work well, thanks for the tip @jasonmit.

The failures look to be unrelated to the PR?

**Comment by GavinJoyce** [comment]
I've upgraded npm and node which seems the have done the trick. Thanks for this 🍻

**Pull request merged**
